image: node:16 # Choose an image matching your project needs
clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly
options:
  docker: true
  size: 2x

definitions:
  services:
    docker:
      memory: 1024
    docker-with-large-memory:
      memory: 5120
      type: docker
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &sonarcloud
        name: Build, test and analyze on SonarCloud
        services:
          - docker-with-large-memory
        size: 2x
        caches:
          - docker
          - node
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.4.0
    - step: &build-test
        name: Build Test
        script:
          - npm install
          - npm run build
          - npm run test
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines: # More info here: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
  branches:
    master:
      - step: *sonarcloud
      - step: *check-quality-gate-sonarcloud
    dev:
      - step: *sonarcloud
      - step: *check-quality-gate-sonarcloud
  pull-requests:
    "**":
      - step: *sonarcloud
      - step: *check-quality-gate-sonarcloud
